# Generated by Django 5.2.8 on 2025-11-05 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
    ]
