# Generated by Django 5.2.8 on 2025-11-05 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_popular_servicos_basicos'),
        ('reservas', '0003_popular_servicos_basicos'),
    ]

    operations = [
    ]
